### ISSUE TITLE
hcard: Error when single telephone # 

### ISSUE THREAD

**Issue by iamjohnford** [mwunsch/prism#1]
When a single telephone number is in an hcard the vcard outputs an error since 'phone' is an unknown variable.

Example: prism --hcard http://www.aldenta.com/

In hcard.rb line 117:

@vcard += "\x0D\x0ATEL#{type_value_vcard(phone)}"

should be changed to:

@vcard += "\x0D\x0ATEL#{type_value_vcard(tel)}"

**Comment by mwunsch** [comment]
Single telephone value to VCARD. Closed by ab82c9f06f82c3d313ad41ab0cb2fed673f02661
