### ISSUE TITLE
hCalendar not working properly

### ISSUE THREAD

**Issue by atd** [mwunsch/prism#4]
Just another bug related with hCalendar,
        Prism.find('http://iansrobinson.com/')
does not find the hCalendar, but mofo and Firefox Operator do.

**Comment by atd** [comment]
In fact, this site rises an error:
        NoMethodError: undefined method `parent' for #<Nokogiri::HTML::Document:0xb6c1ae88>
        from ./prism/posh.rb:58
        from ./prism.rb:92:in`call'
        from ./prism.rb:92:in `valid?'
        from ./prism/posh.rb:161:in`initialize'
        from ./prism/posh.rb:40:in `new'
        from ./prism/posh.rb:40
        from ./prism.rb:108:in`call'
        from ./prism.rb:108:in `extract_from'
        from ./prism.rb:118:in`parse'
        from ./prism/microformat.rb:34:in `find_all'
        from ./prism/microformat.rb:33:in`collect'
        from ./prism/microformat.rb:33:in `find_all'
        from ./prism/microformat.rb:27:in`find'
        from ./prism.rb:10:in `find'
        from (irb):2
        from :0

**Comment by mwunsch** [comment]
No -- hCalendar implementation is not quite complete. I'll be more careful to not push experimental code to master.
